# general
batch_size: 32
optimizer: adamW
loss: CrossEntropyLoss
patience: 20
lr: 'orion~loguniform(1e-5, 1.0)'
architecture: classic-cnn
pretrained: False
max_epoch: 2
exp_name: cnn_test_exp
img_size: 224
num_classes: 31
num_channels: 3
# dataset
data: Office31
# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234
# architecture
num_filters: 4
