experiment:
  name:
    exp_learning_rate
  max_trials: 5
  working_dir:
    orion_working_dir
  algorithms:
    random:
      seed: 1234
evc:
  non_monitored_arguments:
    - output
    - data
    - tmp-folder
  ignore_code_changes:
    true
