# general
batch_size: 16
optimizer: adam
loss: MSELoss
patience: 5
lr: 0.0003
architecture: conv_ae
pretrained: False
max_epoch: 2
exp_name: ae_test_exp
# dataset
data: Office31
img_size: 100
size: 31
num_channels: 3
# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234
# architecture
num_filters: 16

