# general
batch_size: 16
optimizer: adam
loss: BCELoss
patience: 20
lr: 0.001
architecture: conv_ae
pretrained: False
max_epoch: 10
exp_name: ae_test_exp
# dataset
data: Office31
img_size: 224
num_classes: 31
num_channels: 3
data_aug_prob: 0.5
# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234
# architecture
num_filters: 16

