# general
batch_size: 32
optimizer: adamW
loss: CrossEntropyLoss
patience: 5
image_size: 224
lr: 0.0003
architecture: vit
pretrained: False
max_epoch: 1
exp_name: vit_training
# dataset
data: Office31ViT
img_size: 224
num_channels: 3
data_aug_prob: 0.5
# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

